name: fast_trivia
description: A fast-paced and dynamic general knowledge question and answer game.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  asuka: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.0.6+5
  google_fonts: ^5.1.0
  intl: ^0.18.1
  mobx: ^2.2.0
  path: ^1.8.3
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
